name: 🧩 Feature Request
description: Suggest new project functionality
title: "[Feature]: "
labels: [enhancement]
assignees: []
projects: [Factoria-F5-madrid/34]

body:
  - type: markdown
    attributes:
      value: |
        Please complete the following information to describe your proposal

  # - type: input
  #   id: feature_title
  #   attributes:
  #     label: Functionaltity title
  #     placeholder: Brief feature description
  #   validations:
  #     required: true

  - type: textarea
    id: feature_description
    attributes:
      label: Detailed description
      placeholder: What does it do? Why is it useful?
    validations:
      required: true

  # - type: textarea
  #   id: motivation
  #   attributes:
  #     label: Motivation
  #     placeholder: Which problem or necessity solves?
  #   validations:
  #     required: false

  # - type: dropdown
  #   id: priority
  #   attributes:
  #     label: Priority
  #     options:
  #       - High
  #       - Medium
  #       - Low
  #   validations:
  #     required: true
